name: fe CD

on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ develop ]

env:
  S3_BUCKET_NAME: oddokdeploy
  CODE_DEPLOY_APPLICATION_NAME: oddok-code-deploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: oddok

jobs:
  fe:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: client
  
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
        
      - name: Build
        run: npm run build
        env:
          CI: false
        if: ${{ always() }}

      - name: Make zip file
        run: zip -r ./$build-fe.zip .
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$bulid-fe.zip s3://$S3_BUCKET_NAME/client/$bulid-fe.zip
      
      - name: Deploy with AWS Code Deploy
        run: | 
          aws deploy create-deployment
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }}
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }}
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=client/$build-fe.zip
